# Generated by Django 4.2.7 on 2023-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=120)),
                ('imagem', models.ImageField(blank=True, default='', upload_to='listinha/covers/%Y/%m/%d')),
            ],
        ),
    ]
